version: 2.1
executors:
  ci-executor:
    machine:
      image: circleci/classic:201808-01

commands:
  getdependencies:
    description: "Download and cache all the necessary dependencies"
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "package-lock.json" }}
            # Perform a Partial Cache Restore (https://circleci.com/docs/2.0/caching/#restoring-cache)
            - v1-dependencies-
      - run:
          name: Install OpenJDK 11
          command: |
            sudo rm /var/lib/apt/lists/lock
            sudo rm /var/cache/apt/archives/lock
            sudo rm /var/lib/dpkg/lock
            sudo apt install openjdk-11-jdk
            echo 'export PATH="/usr/lib/jvm/java-11-openjdk-amd64/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Setup NVM
          command: |
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run:
          name: Install Node 12.16.1
          command: |
            nvm install 12.16.1
            nvm alias default 12.16.1
      - run:
          name: Print Java Version
          command: 'java -version'
      - run:
          name: Print Node Version
          command: 'node -v'
      - run:
          name: Print NPM Version
          command: 'npm -v'
      - run:
          name: Install Node Modules
          command: 'npm install'
      - save_cache:
          paths:
            - node
            - node_modules
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "package-lock.json" }}
      - run:
          name: Give Executable Power
          command: 'chmod +x gradlew'

jobs:
    build:
        executor: ci-executor
        steps:
            - getdependencies
            - run:
                name: clean and build
                command: './gradlew clean build -x test -x integrationTest --no-daemon'

    unit-test:
        executor: ci-executor
        steps:
            - run:
                name: Run Unit Test
                command: './gradlew clean test  --no-daemon'

    integration-test:
        executor: ci-executor
        steps:
          - getdependencies
          - run:
              name: Run Integration Test
              command: './gradlew clean integrationTest --no-daemon'

    front-end-test:
        executor: ci-executor
        steps:
            - getdependencies
            - run:
                name: Run Front End Tests
                command: npm run test-ci
    verify:
        executor: ci-executor
        steps:
          - getdependencies
          - run:
              name: Verify with Prod Profile
              command: './gradlew bootJar -Pprod -x test -x integrationTest --no-daemon'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit-test:
          requires:
            - build
      - integration-test:
          requires:
            - build
      - front-end-test:
          requires:
            - build
      - verify:
          requires:
            - unit-test
            - integration-test
            - front-end-test
