version: '3.1'
services:
  keycloak:
    image: jboss/keycloak:10.0.0
    environment:
      DB_VENDOR: H2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    volumes:
      - ./realm-config:/opt/jboss/keycloak/realm-config
    ports:
      - 9080:8080
